name: Test Gmail SMTP Authentication and Scrape

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_smtp_authentication_and_scrape:
    runs-on: ubuntu-latest

    env:
      GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 smtplib

      - name: Run SMTP test and scrape script
        run: |
          python Alerts.py
