name: Test Gmail SMTP Authentication

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_smtp_authentication:
    runs-on: ubuntu-latest

    env:
      OUTLOOK_EMAIL: ${{ secrets.GMAIL_EMAIL }}
      OUTLOOK_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run SMTP test script
        run: |
          python test.py
